library(rmarkdown)

render('Module2a_UNIXShell.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module3a_Design_Prep_Seq.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module3a_Design_Prep_Seq_Slides.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module3b_QC.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module4a_Reference_Genomes.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module4a_Reference_Genomes_Slides.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module4b_Alignment.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module7a_IntroductionToR.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module8a_IntroductionToDESeq2.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Module8b_DESeq2Initialization.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
render('Modele8d_DESeq2DifferentialExpression.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
# render('Module9a_SampleVisualizations.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
# render('Module10a_DEComparisons.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
# render('Module10b_DEVisualizations.Rmd', output_dir = 'site', intermediates_dir = 'site', knit_root_dir = 'site')
