---
title: "Introduction to UNIX Shell"
author: "UM Bioinformatics Core"
date: "`r Sys.Date()`"
output:
    html_document:
        theme: readable
        toc: true
        toc_depth: 4
        toc_float: true
        number_sections: true
        fig_caption: true
        keep_md: false
---

<!---
library(rmarkdown)
render('Module2a_UNIXShell.Rmd', output_dir = 'site')
--->

<!--- Allow the page to be wider --->
<style>
    body .main-container {
        max-width: 1200px;
    }
</style>

> # Objectives
> * Understand what a UNIX shell is, and why it is useful.
> * Understand how to navigate the file system in the shell.
> * Understand how to copy, move, and delete files in the shell.
> * Understand how to change the behavior of programs in the shell with flags.

# Background

There are many ways to interact with computers: keyboard and mouse, via touch, or via voice. The **graphical user interface** (GUI) let's us manipulate elements on the screen to accomplish tasks, and it's what we're using right now.

A GUI is an intuitive way to use a computer, but it doesn't scale very well for repetitive tasks. To illustrate this -- and since we're here to learn how to do RNA-seq analysis -- let's imagine that we have 20 samples fresh off the sequencer, and we'd like to know which genes are differentially expressed among various groupings of the samples. Using a GUI we'd likely be clicking through the multiple steps for each sample, and figuring out where an error was made would be difficult.

The Unix shell can help us avoid this. The Unix shell is both a **command-line interface** (CLI) and a scripting language, allowing repetitive tasks to be done automatically and quickly. With the proper commands, the shell can repeat tasks with or without modification as many times as needed. Using the shell, the analysis of the RNA-seq data requires much less of our time. Moreover, the best practices for such an analysis consists of tools which usually *require* the use of the CLI.

# The Shell

The shell is a program where we type commands. It enables us to invoke complex programs like sequence aligners or simple commands that list the contents of a directory. There are different shells, but the most popular Unix shell is Bash, and is the default on most modern versions of Unix and packages providing Unix-like tools for Windows (e.g. gitbash). With macOS Catalina and later, Apple has changed the default shell to zsh, but the behavior is similar enough for our purposes.

Using the shell will take some getting used to. While a GUI naturally presents us with choices to select from, a CLI does not so we must learn commands in a manner not dissimilar from learning a new language. We will cover some essential commands during this module.

The grammar of a shell allows us to combine existing tools into powerful pipelines handling large volumes of data automatically. Sequences of commands can be written in a script, improving the reproducibility of workflows. This is *exactly* what we need for our RNA-seq analysis.

Moreover, the command line is typically the only way to interact with remote machines and high-perforance computing clusters (like Great Lakes). The personal computers that we use on a day-to-day basis simply don't have enough storage, memory, or compute power to analyze an RNA-seq experiment in a reasonable amount of time.

When we open a new shell, we are taken to a **prompt**, indicating the shel is waiting for input.

```
(workshop) rcavalca@ip-172-31-85-127:~$
```

Your shell will look a little different in that it'll have your user name instead of mine. For these lessons *do not type the prompt*, only what comes after it. For the remainder of this lesson I will omit everything prior to `$` at the prompt for simplicity.

# Navigating Files and Directories

The **file system** is the part of the operating system that manages files and directories. You can imagine it like a tree which organizes files and folders. There are several commands frequently used to create, inspect, move, rename, and delete files and directories. Let's go back to our open shell window.

## Current Directory

By default the shell drops you in your home directory. To find out where that is, we can use a command called `pwd`, meaning 'print working directory'. Directories are **places** in the file system, and wherever you are at any particular time is called the **current working directory**. So where is your home directory?

```
$ pwd
/home/rcavalca
```

My response is `/home/rcavalca`: the **path**, or location, of my **home directory**. Your path will look a little different because your home directory is your user name.

## The list Command

The `ls` command lists the contents of the current working directory:

```
$ ls
miniconda3  workshop_data
```

Your results will only contain `miniconda3` at the moment, but we'll get `workshop_data` later in the lesson.

`ls` prints the names of the files and directories in the current working directory. We can get a little more information by using the `-F` **option** (also known as a **switch** or **flag**), which tells `ls` to classify the output by adding a marker to file and directory names indicating what they are:

- a trailing `/` means directory
- `@` means a link
- `*` means an executable
- no mark indicates a file

```
$ ls -F
miniconda3/  workshop_data/
```

Here the home directory only contains **sub-directories**.

## Syntax of a Command

Let's break down the simple command we just used to learn some more terminology:

```
$ ls -F .
miniconda3/  workshop_data/
```

- `ls` is the **command**,
- `-F` is an **option**, **switch**, or **flag**, and
- `.` is an **argument**, in this case `.` means "here", the current directory.

An option or flag can start either with a single dash (`-`) or two dashes (`--`) and they change the behavior of a command. Arguments tell the command what to operate on (e.g. files and directories). Sometimes options and arguments are called **parameters**. Commands can be called with more than one option and more than one argument, but a command doesn't always require them.

Each part is separated by spaces: omitting the space between `ls` and `-F` is telling the shell to look for a command `ls-F`, which doesn't exist. Capitalization can also be important. For example, `ls -s` displays the size of files and directories alongside their names:

```
$ ls -s
total 8
4 miniconda3  4 workshop_data
```

While `ls -S` sorts the files and directories by their sizes:

```
$ ls -S
miniconda3  workshop_data
```

## The copy command

The copy command, `cp`, is helpful for duplicating items. Let's copy the data we are going to use in the lessons later in the day. Let's be sure to use the `-r` flag, meaning recursive. This will copy everything in the directory.

```
$ cp -r /home/rcavalca/workshop_data .
cp: '/home/rcavalca/workshop_data' and './workshop_data' are the same file
```

**Note**, we have again used the `.` to indicate "here". Only I should see an error because I'm trying to copy something to itself. After hitting enter, you should be at the next line in the command prompt. Some shell commands don't output messages unless there is an error.

## The tree Command

When we navigate a file system in a GUI, the directory structure is clear to us. With the command line, there is a helpful command called `tree` that helps us see the structure. Let's type the following command to see what's included in the `workshop_data` folder we just copied.

```
$ tree workshop_data
workshop_data
├── example.genes.results
├── example.genome.bam
├── example.genome.sam
├── fastqs
│   ├── example_R1.fastq.gz
│   ├── example_R2.fastq.gz
│   └── example_sra.fastq
└── human_reference
    ├── GRCh38
    │   ├── GRCh38.98.gtf
    │   └── GRCh38.fa
    └── hg19
        ├── genome.fa
        └── hg19_genes.gtf

4 directories, 10 files
```

This is a helpful way to hierarchically view the folders and files in the filesystem. **Warning**, `tree` can sometimes surprise you with its prolific output (depending on how many sub-folders and sub-directories there are). In the next section, we'll see how to find out more about commands and their options.

# Getting Help

Commands can have many options, and the syntax for calling a command isn't always clear. The `--help` flag or the `man` command can be used to learn more about a commands options and syntax. Let's look at the help for `tree` to see if there's a way to limit its output.

## The help flag

Many bash commands, and programs written by others, support the `--help` (sometimes `-h`) option to show more information on how to use the command or program. Here is the output for `tree --help`. Notice the `-L` flag is what we were looking for.

```
$ tree --help
usage: tree [-acdfghilnpqrstuvxACDFJQNSUX] [-H baseHREF] [-T title ]
	[-L level [-R]] [-P pattern] [-I pattern] [-o filename] [--version]
	[--help] [--inodes] [--device] [--noreport] [--nolinks] [--dirsfirst]
	[--charset charset] [--filelimit[=]#] [--si] [--timefmt[=]<f>]
	[--sort[=]<name>] [--matchdirs] [--ignore-case] [--] [<directory list>]
  ------- Listing options -------
  -a            All files are listed.
  -d            List directories only.
  -l            Follow symbolic links like directories.
  -f            Print the full path prefix for each file.
  -x            Stay on current filesystem only.
  -L level      Descend only level directories deep.
  -R            Rerun tree when max dir level reached.
  -P pattern    List only those files that match the pattern given.
  -I pattern    Do not list files that match the given pattern.
  --ignore-case Ignore case when pattern matching.
  --matchdirs   Include directory names in -P pattern matching.
  --noreport    Turn off file/directory count at end of tree listing.
  --charset X   Use charset X for terminal/HTML and indentation line output.
  --filelimit # Do not descend dirs with more than # files in them.
  --timefmt <f> Print and format time according to the format <f>.
  -o filename   Output to file instead of stdout.
  -------- File options ---------
  -q            Print non-printable characters as '?'.
  -N            Print non-printable characters as is.
  -Q            Quote filenames with double quotes.
  -p            Print the protections for each file.
  -u            Displays file owner or UID number.
  -g            Displays file group owner or GID number.
  -s            Print the size in bytes of each file.
  -h            Print the size in a more human readable way.
  --si          Like -h, but use in SI units (powers of 1000).
  -D            Print the date of last modification or (-c) status change.
  -F            Appends '/', '=', '*', '@', '|' or '>' as per ls -F.
  --inodes      Print inode number of each file.
  --device      Print device ID number to which each file belongs.
  ------- Sorting options -------
  -v            Sort files alphanumerically by version.
  -t            Sort files by last modification time.
  -c            Sort files by last status change time.
  -U            Leave files unsorted.
  -r            Reverse the order of the sort.
  --dirsfirst   List directories before files (-U disables).
  --sort X      Select sort: name,version,size,mtime,ctime.
  ------- Graphics options ------
  -i            Don't print indentation lines.
  -A            Print ANSI lines graphic indentation lines.
  -S            Print with CP437 (console) graphics indentation lines.
  -n            Turn colorization off always (-C overrides).
  -C            Turn colorization on always.
  ------- XML/HTML/JSON options -------
  -X            Prints out an XML representation of the tree.
  -J            Prints out an JSON representation of the tree.
  -H baseHREF   Prints out HTML format with baseHREF as top directory.
  -T string     Replace the default HTML title and H1 header with string.
  --nolinks     Turn off hyperlinks in HTML output.
  ---- Miscellaneous options ----
  --version     Print version and exit.
  --help        Print usage and this help message and exit.
  --            Options processing terminator.
```

## The manual command

The other way to learn about `tree` is to type:

```
$ man tree
```

This turns the terminal into a page with a description of the `ls` command and its options.

To navigate a `man` page, use the up/down arrow keys to move line-by-line or the PageUp/PageDown keys to skip up and down by a full page. To quit the `man` page, press `Q`.

Manual pages can also be found on the internet, for example [https://www.explainshell.com](https://explainshell.com) is a handy webiste that will break down the components of shell commands.

# Mistakes are okay!

We all hit the wrong key now and then. The shell will often alert you to this fact, sometimes with helpful messages.

```
$ ks -F
command not found: ks
```

Here we might have had `ls` in mind, but the shell simply tells us that `ks` is not a valid command. If we try to use a flag that doesn't exist we get something a bit more helpful:

```
$ ls -j
ls: illegal option -- j
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]
```

# Exploring other directories

The `ls` command can also be used to look into other directories. We used `tree` above to look inside `workshop_data`, but we also could have used `ls`.

```
$ ls workshop_data/
example.genes.results  example.genome.bam  example.genome.sam  fastqs  human_reference
```

We could go a little further and look inside `fastqs` inside `workshop_data` with:

```
$ ls workshop_data/fastqs
example_R1.fastq.gz  example_R2.fastq.gz  example_sra.fastq
```

## The cd command

We can change our location to a different directory with the 'change directory' or `cd` command. You can think of `cd` as the same as double clicking a folder in a GUI to move into a folder. If we want to move into the `alignments` directory we can:

```
$ cd workshop_data
$ cd fastqs
```

This moves us into `workshop_data`, then into `fastqs`. This is another example of a command not outputting anything unless there is an error.

Now if we run `pwd`, we'll see the change in directory (your path will look slightly different):

```
$ pwd
/home/rcavalca/workshop_data/fastqs
```

Let's try invoking `ls` with a new option, `-l` for list format:

```
$ ls -l
total 6624
-rw-rw-r-- 1 rcavalca rcavalca 3236531 Dec 14 12:10 example_R1.fastq.gz
-rw-rw-r-- 1 rcavalca rcavalca 3535293 Dec 14 12:10 example_R2.fastq.gz
-rw-rw-r-- 1 rcavalca rcavalca    1912 Dec 14 12:10 example_sra.fastq
```

This shows us the contents of the directory in a list format, with quite a bit more information. It tells us

* who is allowed to do what with the file (`-rw-rw-r--`),
* who owns the file (`rcavalca`),
* how big it is in bytes (3236531),
* when it was last modified (Dec 13 16:12)
* and the name of the file (example_R1.fastq.gz)

### Going back a directory

We have gone down into `workshop_data/fastqs`, but how do we get back up to `workshop_data`?

```
$ cd workshop_data
cd: no such file or directory: workshop_data
```

But this doesn't work because `workshop_data` isn't in `fastqs`. There is a special way to refer to "the directory above me", or the parent directory. That is `..`.

```
$ cd ..
```

If we then do `pwd` we see we've gone up to `workshop_data`.

```
$ pwd
/home/rcavalca/workshop_data
```

The basic commands for navigating the file system in a shell on your computer are `pwd`, `ls`, `cd`, and possibly `tree`. Let's quickly explore some variations on these commands to explore some further shell concepts. What happens if we call `cd` without giving a directory?

```
$ cd
```

We know that `pwd` will tell us where we are, so calling it tells us:

```
$ pwd
/home/rcavalca
```

So `cd` with no arguments takes us to our home directory. Let's return to the `workshop_data/fastqs` directory from before. Last time, we used two commands, but we can do it in one step:

```
$ cd workshop_data/fastqs
```

You can check that we're in the right place by doing `pwd` and `ls -F`. We discussed the use of `..` to move up directories, but there is another way to move around the file system.

When we've been giving directory names, or even a path (like `workshop_data/fastqs`), these have been **relative paths**. That is to say, they were relative to the current working directory.

We could use the **absolute path** to the directory by including the entire path from the root directory. An absolute path always refers to exactly one directory, no matter our working directoy when running the command.

So to go up to the `workshop_data` directory we could:

```
$ cd /home/rcavalca/workshop_data
```

Note, your path will depend on your user name.

# Altering files and directories

## Creating directories

We've just learned how to explore files and directories, but how do we create them? A good place to start is to see where we are and what we have. Going back to `workshop_data`:

```
$ cd ~/workshop_data
$ ls -F
example.genes.results  example.genome.bam  example.genome.sam  fastqs/  human_reference/
```

Let's make a new directory for the `example` files called `rsem_star`:

```
$ mkdir rsem_star
```

The `mkdir` command means 'make directory'. Since we gave a relative path, it was created in the working directory:

```
$ ls -F
example.genes.results  example.genome.bam  example.genome.sam  fastqs/  human_reference/  rsem_star/
```

Since we just made it, there's nothing in it, which is indicated by nothing being returned:

```
$ ls -F rsem_star
$
```

> **A note on names**
>
> Complicated names can cause difficulty later on by making it difficult to remember and difficult to type the names of directories or files. Some tips for naming files and directories:
>
> 1. Don't use spaces. Instead use `-` or `_` to separate words, e.g. `example_R1.fastq.gz`.
>
> 2. Don't begin names with `-` because commands treat such names as options.
>
> 3. Stick with letters, numbers, `.`s, `-`s, and `_`s. Many characters have special meanings, so it's best to avoid them.
>
> If you inherit files or directories with spaces or other special characters, surround the name in quotes (`""`).

## Moving files and directories

Let's say that we want to move the files `example.genes.results`, `example.genome.bam`, and `example.genome.sam` into the `rsem_star` folder we just created. We can do that with the move command `mv`:

```
$ mv example.genes.results rsem_star
$ mv example.genome.bam rsem_star
$ mv example.genome.sam rsem_star
```

The first argument tells `mv` what we're moving (the **source**) and the second is where it should go (the **target**). If we check with `tree`, we'll see that the file has been moved:

```
$ tree .
.
├── fastqs
│   ├── example_R1.fastq.gz
│   ├── example_R2.fastq.gz
│   └── example_sra.fastq
├── human_reference
│   ├── GRCh38
│   │   ├── GRCh38.98.gtf
│   │   └── GRCh38.fa
│   └── hg19
│       ├── genome.fa
│       └── hg19_genes.gtf
└── rsem_star
    ├── example.genes.results
    ├── example.genome.bam
    └── example.genome.sam

5 directories, 10 files
```

We should be careful when specifying the target file name because `mv` silently overwrites any existing file with the same name, which could cause data loss. The `-i` option (`mv -i` or `mv --interactive`), will ask for confirmation before moving.

Note, `mv` also works on directories. Say we want to change the name of the directory `human_reference` to `human_reference_genomes`. We could do that with (but let's not):

```
$ mv human_reference human_reference_genomes
```

## Removing files and directories

The `rm`, or remove, command allows us to delete files. Unlike Windows or macOS, UNIX has no notion of a Recycle Bin or Trash from which you can retrieve deleted items. In other words **deletion is forever** (usually). So treat carefully and use the `-i` flag to interactively say whether you want to delete each file. Let's exercise that on `fastqs/example_sra.fastq`, but decide not to delete it. If you do, that's okay, we're not going to use it later anyway.

```
$ cd ~/workshop_data
$ rm -i fastqs/example_sra.fastq
rm: remove regular file 'fastqs/example_sra.fastq'? n
```

Directories have to be removed with an addition `-r` recursive flag. Using the `-i` flag is **highly recommended**. Although, an alternative approach to deleting files is to "move them out of the way" by renaming them.

# Summary

In this lesson we've learned:

- What a shell is.
- Why it is useful.
- How to navigate the file system.
- How to manipulate files and folders.

We have only scratched the surface of what is possible with the commands available in the Unix shell.

---

These materials have been adapted and extended from materials created by the [Software Carpentry](https://swcarpentry.github.io/shell-novice/). These are open access materials distributed under the terms of the [Creative Commons Attribution license (CC BY 4.0)](http://creativecommons.org/licenses/by/4.0/), which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.
